project:
  type: website

website:
  title: "Martin Oscarsson"
  navbar:
    pinned: true
    background: white
    search: false
    left:
      - href: publications.qmd
        text: Publications
      - href: conferences.qmd
        text: Conferences
      - href: press.qmd
        text: Press

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: false