---
title: "Conferences"
---

::: {.long-page}

Peer-reviewed conference contributions:

**Oscarsson, M.**, Monasterio, F., Wall, K., Rozental, A., Ginsberg, Y., Carlbring, P., Andersson, G., & Jönsson, F. (2025, October 3–5). *Internet-based cognitive-behavioral and mindfulness-based stress management for adult ADHD: A randomized controlled trial* [Conference presentation]. 8th European Society for Research on Internet Interventions (ESRII) Conference, Vilnius, Lithuania. [https://urn.kb.se/resolve?urn=urn:nbn:se:su:diva-248207](https://urn.kb.se/resolve?urn=urn:nbn:se:su:diva-248207)

**Oscarsson, M.**, Monasterio, F., Wall, K., Rozental, A., Ginsberg, Y., Carlbring, P., Andersson, G., & Jönsson, F. (2025, September 23–25). *Internet-based cognitive-behavioral and mindfulness interventions for stress and work-related mental health in adults with ADHD: A randomized controlled trial* [Poster presentation]. EUNETHYDIS 36th Annual Meeting, Bonn, Germany. [https://urn.kb.se/resolve?urn=urn:nbn:se:su:diva-247713](https://urn.kb.se/resolve?urn=urn:nbn:se:su:diva-247713)

**Oscarsson, M.**, Rozental, A., Ginsberg, Y., Carlbring, P., Andersson, G., & Jönsson, F. (2024, November 28–29). *Managing work-related mental health in adults with ADHD: A randomized controlled trial of internet-based cognitive-behavioral and mindfulness interventions* [Conference presentation]. The Swedish Conference of Clinical Psychology, Stockholm, Sweden. [https://urn.kb.se/resolve?urn=urn:nbn:se:su:diva-241076](https://urn.kb.se/resolve?urn=urn:nbn:se:su:diva-241076)

**Oscarsson, M.**, Rozental, A., Ginsberg, Y., Carlbring, P., Andersson, G., & Jönsson, F. (2024, September 4–7). *Evaluating online cognitive-behavioral and mindfulness interventions for adults with ADHD: A randomized controlled trial* [Conference presentation]. 54th Annual Congress of the European Association for Behavioural and Cognitive Therapies, Belgrade, Serbia. [https://urn.kb.se/resolve?urn=urn:nbn:se:su:diva-233951](https://urn.kb.se/resolve?urn=urn:nbn:se:su:diva-233951)

**Oscarsson, M.**, Rozental, A., Ginsberg, Y., Carlbring, P., Andersson, G., & Jönsson, F. (2024, May 22–23). *Internet interventions for working adults with ADHD: A randomized trial of cognitive-behavioral versus mindfulness stress-management*. In *Abstracts from the 13th Swedish Congress on Internet Interventions (SweSRII)* (p. 7). Linköping University Electronic Press. [https://urn.kb.se/resolve?urn=urn:nbn:se:su:diva-231480](https://urn.kb.se/resolve?urn=urn:nbn:se:su:diva-231480)

**Oscarsson, M.**, Rozental, A., Ginsberg, Y., Carlbring, P., Andersson, G., & Jönsson, F. (2023, June 1–4). *A novel internet-based cognitive-behavioral stress-management program for working adults with ADHD* [Conference presentation]. 10th World Congress of Cognitive and Behavioral Therapies, Seoul, South Korea. [https://urn.kb.se/resolve?urn=urn:nbn:se:su:diva-218886](https://urn.kb.se/resolve?urn=urn:nbn:se:su:diva-218886)

Kjellberg, A., Holmberg, L., **Oscarsson, M.**, & Forsström, D. (2023, May 22–23). *Treatment-related helping and hindering factors for iCBT for ADHD symptoms: A qualitative study* [Conference presentation]. 12th Swedish Congress on Internet Interventions (SweSRII), Uppsala, Sweden. [https://urn.kb.se/resolve?urn=urn:nbn:se:su:diva-218871](https://urn.kb.se/resolve?urn=urn:nbn:se:su:diva-218871)

Engström, E., Olsson, E., **Oscarsson, M.**, & Forsström, D. (2023, May 22–23). *Outcome of iCBT for ADHD symptoms: A randomized controlled study* [Conference presentation]. 12th Swedish Congress on Internet Interventions (SweSRII), Uppsala, Sweden. [https://urn.kb.se/resolve?urn=urn:nbn:se:su:diva-218872](https://urn.kb.se/resolve?urn=urn:nbn:se:su:diva-218872)

Mahdi, S., **Oscarsson, M.**, Åberg, A., Hammarlund, K., Tallert, C., Cloodt, H., Zander, E., Kaldo, V., & Nasri, B. (2023, May 18–21). *Short ADHD intervention (SAINT): Psychological treatment for adults with ADHD* [Poster presentation]. 9th World Congress on ADHD, Amsterdam, Netherlands. [https://urn.kb.se/resolve?urn=urn:nbn:se:su:diva-218862](https://urn.kb.se/resolve?urn=urn:nbn:se:su:diva-218862)

**Oscarsson, M.**, Rozental, A., Ginsberg, Y., Carlbring, P., Andersson, G., & Jönsson, F. (2023, May 18–21). *A pilot study of an internet-based stress-management program for working adults with ADHD* [Early Career Researcher Meeting presentation]. 9th World Congress on ADHD, Amsterdam, Netherlands. [https://urn.kb.se/resolve?urn=urn:nbn:se:su:diva-218855](https://urn.kb.se/resolve?urn=urn:nbn:se:su:diva-218855)

**Oscarsson, M.**, Nelson, M., Rozental, A., Ginsberg, Y., Carlbring, P., & Jönsson, F. (2023, May 18–21). *A qualitative study of stress and work-related mental illness among working adults with attention-deficit/hyperactivity disorder* [Poster presentation]. 9th World Congress on ADHD, Amsterdam, Netherlands. [https://urn.kb.se/resolve?urn=urn:nbn:se:su:diva-218857](https://urn.kb.se/resolve?urn=urn:nbn:se:su:diva-218857)

**Oscarsson, M.**, Nelson, M., Rozental, A., Ginsberg, Y., Carlbring, P., & Jönsson, F. (2022, May 23–24). *Developing an internet-based stress-management program for working adults with ADHD*. In *Abstracts from the 11th Swedish Congress on Internet Interventions (SweSRII)* (p. 9). Linköping University Electronic Press. [http://urn.kb.se/resolve?urn=urn:nbn:se:su:diva-208137](http://urn.kb.se/resolve?urn=urn:nbn:se:su:diva-208137)

**Oscarsson, M.**, Rozental, A., Andersson, G., & Carlbring, P. (2017, November 3). *New Year’s resolutions: A large-scale randomized controlled trial*. In *Abstracts from the 9th Swedish Congress on Internet Interventions (SweSRII)* (p. 11). Linköping University Electronic Press. [http://urn.kb.se/resolve?urn=urn:nbn:se:su:diva-149191](http://urn.kb.se/resolve?urn=urn:nbn:se:su:diva-149191)

:::